# See help here: https://docs.github.com/en/free-pro-team@latest/github/administering-a-repository/enabling-and-disabling-version-updates

version: 2
updates:
  #
  # Github actions - CI
  #
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: "daily"
      time: "09:00"
      timezone: "Europe/Dublin"
    open-pull-requests-limit: 3
    
  #
  # Enable version updates for npm
  #
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
      time: "09:00"
      timezone: "Europe/Dublin"
    open-pull-requests-limit: 3
    versioning-strategy: increase-if-necessary
    
  #
  # Python dependencies (UV workspace)
  #
  - package-ecosystem: "uv"
    directory: "/"
    schedule:
      interval: "daily"
      time: "09:00"
      timezone: "Europe/Dublin"
    open-pull-requests-limit: 5
